services:
  - type: web
    name: scraper-backend
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    preDeployCommand: |
      apt-get update && \
      apt-get install -y wget gnupg && \
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
      echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
      apt-get update && \
      apt-get install -y google-chrome-stable
    envVars:
      - key: SHEET_NAME
        # This is a placeholder. You will set the real value in the Render dashboard.
        value: "My Scraped Business Data"
      - key: GOOGLE_CREDENTIALS_JSON
        # IMPORTANT: You will set this secret value in the Render dashboard after creation.
        value: ""